# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-11 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ch', models.CharField(max_length=50)),
                ('name_en', models.CharField(max_length=50)),
                ('magnet_link', models.CharField(default='暂无', max_length=500)),
                ('thunder_link', models.CharField(default='暂无', max_length=300)),
                ('publist_date', models.CharField(default='不详', max_length=20)),
                ('movie_length', models.CharField(default='--:--', max_length=10)),
                ('download_count', models.IntegerField()),
            ],
            options={
                'verbose_name': '电影信息',
                'verbose_name_plural': '电影信息',
                'db_table': 'Movie_info',
            },
        ),
    ]
