# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-11 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=40)),
                ('headpic', models.ImageField(upload_to='head_pic')),
                ('birth', models.DateField(auto_now_add=True)),
                ('gender', models.CharField(max_length=1)),
                ('email', models.CharField(max_length=20)),
                ('level', models.IntegerField(default=0)),
                ('desc', models.CharField(blank=True, max_length=100, null=True)),
                ('isdeleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
                'db_table': 'Userinfo',
            },
        ),
    ]
