# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-11 11:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contentinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='标题')),
                ('content', tinymce.models.HTMLField(blank=True, max_length=5000, verbose_name='内容')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.Userinfo', verbose_name='作者')),
            ],
            options={
                'verbose_name': '文章信息',
                'verbose_name_plural': '文章信息',
                'db_table': 'Contentinfo',
            },
        ),
        migrations.CreateModel(
            name='Contenttype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20, verbose_name='文章分类')),
            ],
            options={
                'verbose_name': '文章分类',
                'verbose_name_plural': '文章分类',
                'db_table': 'Contenttype',
            },
        ),
        migrations.AddField(
            model_name='contentinfo',
            name='ttype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Content.Contenttype', verbose_name='文章分类'),
        ),
    ]
